# Streamlit Cloud Secrets Configuration
# This file contains configuration for Streamlit Cloud deployment
# Add any sensitive configuration here (API keys, database URLs, etc.)

[general]
app_name = "Advanced Diabetes Risk Predictor"
version = "2.0.0"
environment = "production"

# Model configuration
[model]
cache_ttl = 3600  # Cache model for 1 hour
max_predictions_per_session = 100

# UI configuration
[ui]
show_debug_info = false
enable_analytics = true
max_history_entries = 50

# Performance settings
[performance]
enable_caching = true
cache_persist = true
memory_limit_mb = 1024

# Security settings
[security]
enable_input_validation = true
sanitize_inputs = true
rate_limit_enabled = true

# Note: This is a template file. 
# In production, you would add actual secrets here through the Streamlit Cloud interface.